import { router } from 'expo-router';
import { CreditCard, Plus, X } from 'lucide-react-native';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, TextInput, View } from 'react-native';

import { AppText, Divider, EmptyState, PrimaryButton, Screen, Surface } from '@/components/ui';
import { SyncRetry } from '@/components/SyncRetry';
import { radii, spacing, type } from '@/constants/theme';
import { useFinanceData } from '@/hooks/useFinanceData';
import { createOnlineCard } from '@/lib/financialRepository';
import { formatCentsInput, formatMoney, parseBrlToCents } from '@/lib/format';
import { useAuth } from '@/providers/AuthProvider';
import { useAppTheme } from '@/providers/ThemeProvider';
import { useFinanceStore } from '@/store/useFinanceStore';

export default function CardsScreen() {
  const { user } = useAuth(); const { palette } = useAppTheme(); const finance = useFinanceData(); const addLocalCard = useFinanceStore((state) => state.addCard);
  const [adding, setAdding] = useState(false); const [saving, setSaving] = useState(false); const [name, setName] = useState(''); const [institution, setInstitution] = useState(''); const [lastFour, setLastFour] = useState(''); const [limitCents, setLimitCents] = useState(0); const [closingDay, setClosingDay] = useState('25'); const [dueDay, setDueDay] = useState('5');

  async function save() {
    const closing = Number(closingDay); const due = Number(dueDay);
    if (name.trim().length < 2 || institution.trim().length < 2) return Alert.alert('Dados do cartão', 'Preencha o nome e a instituição.');
    if (lastFour && !/^\d{4}$/.test(lastFour)) return Alert.alert('Final do cartão', 'Digite exatamente os 4 últimos números ou deixe em branco.');
    if (limitCents <= 0) return Alert.alert('Limite', 'Digite um limite maior que zero.');
    if (closing < 1 || closing > 31 || due < 1 || due > 31) return Alert.alert('Datas inválidas', 'Fechamento e vencimento devem estar entre 1 e 31.');
    if (!user) return; setSaving(true);
    try {
      if (user.demo) addLocalCard({ ownerId: user.memberId, name: name.trim(), lastFour: lastFour || undefined, limitCents, closingDay: closing, dueDay: due });
      else { if (!finance.householdId) throw new Error('A Família A&T ainda não terminou de sincronizar.'); await createOnlineCard({ householdId: finance.householdId, userId: user.id, name, institution, lastFour: lastFour || undefined, limitCents, closingDay: closing, dueDay: due }); await finance.refresh(); }
      setAdding(false); setName(''); setInstitution(''); setLastFour(''); setLimitCents(0);
    } catch (reason) { Alert.alert('Cartão não adicionado', reason instanceof Error ? reason.message : 'Tente novamente.'); } finally { setSaving(false); }
  }

  return <KeyboardAvoidingView style={[styles.flex, { backgroundColor: palette.ink }]} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><Screen>
    <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Fechar" onPress={() => router.back()} style={[styles.close, { backgroundColor: palette.surface }]}><X size={20} color={palette.text} /></Pressable><AppText variant="section">Cartões e faturas</AppText><View style={styles.close} /></View>
    {!adding ? <><View style={styles.summary}><View><AppText variant="label">FATURAS ATUAIS</AppText><AppText variant="title">{formatMoney(finance.cards.reduce((sum, item) => sum + item.usedCents, 0))}</AppText></View><Pressable accessibilityRole="button" accessibilityLabel="Adicionar cartão" onPress={() => setAdding(true)} style={[styles.add, { backgroundColor: palette.mint }]}><Plus size={22} color={palette.ink} /></Pressable></View>
      <Surface style={styles.list}>{finance.cards.length ? finance.cards.map((item, index) => { const progress = Math.min(1, item.usedCents / item.limitCents); return <View key={item.id}>{index ? <Divider /> : null}<Pressable accessibilityRole="button" accessibilityLabel={`Ver detalhes de ${item.name}`} onPress={() => Alert.alert(item.name, `Fatura e limite usados: ${formatMoney(item.usedCents)}\nLimite disponível: ${formatMoney(Math.max(0, item.limitCents - item.usedCents))}\nFecha dia ${item.closingDay} · vence dia ${item.dueDay}\nTitular: ${item.ownerId === 'alberto' ? 'Alberto' : 'Thauane'}`)} style={({ pressed }) => [styles.cardRow, pressed && styles.rowPressed]}><View style={[styles.icon, { backgroundColor: palette.skyDeep }]}><CreditCard size={20} color={palette.sky} /></View><View style={styles.cardCopy}><View style={styles.line}><AppText variant="body">{item.name}</AppText><AppText variant="mono" style={styles.money}>{formatMoney(item.usedCents)}</AppText></View><AppText variant="caption">final {item.lastFour ?? 'não informado'} · vence dia {item.dueDay} · {item.ownerId === 'alberto' ? 'Alberto' : 'Thauane'}</AppText><View style={[styles.track, { backgroundColor: palette.lineSoft }]}><View style={[styles.fill, { width: `${progress * 100}%`, backgroundColor: progress > .85 ? palette.danger : palette.sky }]} /></View><AppText variant="caption">{Math.round(progress * 100)}% de {formatMoney(item.limitCents)}</AppText></View></Pressable></View>; }) : <EmptyState title="Nenhum cartão cadastrado" description="Adicione um cartão para registrar compras e escolher o número de parcelas." />}</Surface>
      {!finance.cards.length ? <PrimaryButton label="Adicionar primeiro cartão" onPress={() => setAdding(true)} /> : null}
      {finance.error ? <SyncRetry busy={finance.isRefreshing} onRetry={finance.refresh} tone="amber" title="Atualizar cartões e faturas" description="Vamos conferir a sessão, os cartões e as faturas do casal." /> : null}
    </> : <><View style={styles.formHeading}><AppText variant="title">Adicionar cartão</AppText><AppText variant="bodyMuted">Somente os quatro últimos números são armazenados.</AppText></View><Field label="Nome do cartão" value={name} onChangeText={setName} placeholder="Ex.: Nubank Alberto" /><Field label="Instituição" value={institution} onChangeText={setInstitution} placeholder="Ex.: Nubank" /><Field label="Quatro últimos números (opcional)" value={lastFour} onChangeText={(value) => setLastFour(value.replace(/\D/g, '').slice(0, 4))} placeholder="0000" keyboardType="number-pad" /><View style={styles.field}><AppText variant="label">Limite</AppText><TextInput accessibilityLabel="Limite" keyboardType="number-pad" value={formatCentsInput(limitCents)} onChangeText={(value) => setLimitCents(parseBrlToCents(value))} style={[styles.input, { backgroundColor: palette.surface, color: palette.text }]} selectionColor={palette.mint} /></View><View style={styles.days}><Field label="Fecha no dia" value={closingDay} onChangeText={(value) => setClosingDay(value.replace(/\D/g, '').slice(0, 2))} placeholder="25" keyboardType="number-pad" compact /><Field label="Vence no dia" value={dueDay} onChangeText={(value) => setDueDay(value.replace(/\D/g, '').slice(0, 2))} placeholder="5" keyboardType="number-pad" compact /></View><View style={styles.actions}><PrimaryButton label="Salvar cartão" loading={saving} onPress={() => void save()} /><Pressable onPress={() => setAdding(false)} style={styles.cancel}><AppText variant="label" style={{ color: palette.text }}>Cancelar</AppText></Pressable></View></>}
  </Screen></KeyboardAvoidingView>;
}

function Field({ label, value, onChangeText, placeholder, keyboardType, compact }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; keyboardType?: 'number-pad'; compact?: boolean }) { const { palette } = useAppTheme(); return <View style={[styles.field, compact && styles.compact]}><AppText variant="label">{label}</AppText><TextInput accessibilityLabel={label} maxLength={80} keyboardType={keyboardType} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={palette.textDim} selectionColor={palette.mint} style={[styles.input, { backgroundColor: palette.surface, color: palette.text }]} /></View>; }
const styles = StyleSheet.create({ flex: { flex: 1 }, header: { paddingTop: spacing.md, minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, close: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, summary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, add: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, list: { paddingVertical: spacing.xs }, cardRow: { minHeight: 104, flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, paddingVertical: spacing.md, borderRadius: radii.sm }, rowPressed: { opacity: 0.62 }, icon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, cardCopy: { flex: 1, gap: spacing.xs }, line: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, money: { fontSize: 13 }, track: { height: 5, borderRadius: radii.pill, overflow: 'hidden', marginTop: spacing.xs }, fill: { height: '100%', borderRadius: radii.pill }, formHeading: { gap: spacing.xs }, field: { gap: spacing.sm }, compact: { flex: 1 }, input: { minHeight: 54, borderRadius: radii.md, paddingHorizontal: spacing.lg, fontFamily: type.regular, fontSize: 16 }, days: { flexDirection: 'row', gap: spacing.md }, actions: { gap: spacing.sm }, cancel: { minHeight: 46, alignItems: 'center', justifyContent: 'center' } });
