import * as Application from 'expo-application';
import { router } from 'expo-router';
import { KeyRound, LockKeyhole, LogOut, ShieldCheck, Smartphone, X } from 'lucide-react-native';
import { useState } from 'react';
import { Alert, Platform, Pressable, StyleSheet, View } from 'react-native';

import { AppText, Divider, Screen, Surface } from '@/components/ui';
import { colors, radii, spacing } from '@/constants/theme';
import { useAuth } from '@/providers/AuthProvider';
import { useAppTheme } from '@/providers/ThemeProvider';

function SecurityRow({ icon, title, detail, onPress, danger = false }: { icon: React.ReactNode; title: string; detail: string; onPress?: () => void; danger?: boolean }) {
  const { palette } = useAppTheme();
  const content = <><View style={[styles.icon, { backgroundColor: danger ? palette.dangerDeep : palette.mintDeep }]}>{icon}</View><View style={styles.copy}><AppText variant="body" style={danger ? { color: palette.danger } : undefined}>{title}</AppText><AppText variant="caption">{detail}</AppText></View></>;
  return onPress ? <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.row, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.row}>{content}</View>;
}

export default function SecurityScreen() {
  const { user, requestPasswordReset, signOut } = useAuth(); const { palette } = useAppTheme(); const [sending, setSending] = useState(false);
  async function resetPassword() { if (!user?.email || sending) return Alert.alert('Email indisponível', 'Entre novamente com seu email para alterar a senha.'); setSending(true); try { await requestPasswordReset(user.email); Alert.alert('Email enviado', `Confira ${user.email} e toque no link seguro para abrir a troca de senha no aplicativo.`); } catch (reason) { Alert.alert('Email não enviado', reason instanceof Error ? reason.message : 'Tente novamente.'); } finally { setSending(false); } }
  function logout() { Alert.alert('Sair deste aparelho?', 'A sessão local será encerrada. Os dados compartilhados permanecem protegidos no servidor.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Sair', style: 'destructive', onPress: () => void signOut() }]); }
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Fechar" onPress={() => router.back()} style={[styles.close, { backgroundColor: palette.surface }]}><X size={20} color={palette.text} /></Pressable><AppText variant="section">Segurança</AppText><View style={styles.close} /></View><View style={styles.hero}><View style={[styles.heroIcon, { backgroundColor: palette.mintDeep }]}><ShieldCheck size={28} color={palette.mint} /></View><AppText variant="title">Sessão protegida</AppText><AppText variant="bodyMuted" style={styles.center}>Credenciais ficam no armazenamento seguro do aparelho. O banco limita cada consulta à Família A&T.</AppText></View><Surface style={styles.list}><SecurityRow icon={<LockKeyhole size={19} color={palette.mint} />} title="Login atual" detail={user?.email ?? `${user?.name} · modo local`} /><Divider /><SecurityRow icon={<Smartphone size={19} color={palette.mint} />} title="Este aparelho" detail={`${Platform.OS === 'android' ? 'Android' : Platform.OS === 'ios' ? 'iPhone' : 'Navegador'} · versão ${Application.nativeApplicationVersion ?? 'desenvolvimento'}`} />{!user?.demo ? <><Divider /><SecurityRow icon={<KeyRound size={19} color={palette.mint} />} title={sending ? 'Enviando email…' : 'Trocar senha'} detail="Envia um link seguro para seu email" onPress={() => void resetPassword()} /></> : null}<Divider /><SecurityRow danger icon={<LogOut size={19} color={palette.danger} />} title="Sair deste aparelho" detail="Encerra somente esta sessão" onPress={logout} /></Surface><View style={styles.note}><ShieldCheck size={16} color={palette.mint} /><AppText variant="caption" style={styles.noteText}>O aplicativo nunca armazena senha, chave da IA ou chave privada dentro do código.</AppText></View></Screen>;
}
const styles = StyleSheet.create({ header: { paddingTop: spacing.md, minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, close: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, hero: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.lg }, heroIcon: { width: 58, height: 58, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.sm }, center: { textAlign: 'center', maxWidth: 320 }, list: { paddingVertical: spacing.xs }, row: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderRadius: radii.sm }, pressed: { opacity: .65 }, icon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, gap: 3 }, note: { flexDirection: 'row', justifyContent: 'center', gap: spacing.sm, paddingHorizontal: spacing.lg }, noteText: { flexShrink: 1 }, danger: { color: colors.danger } });
